CREATE TABLE PACIENTE (
    id_paciente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) UNIQUE NOT NULL,
    data_nascimento DATE,
    telefone VARCHAR2(15),
    endereco VARCHAR2(200)
);

CREATE TABLE ENFERMEIRO (
    id_enfermeiro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    coren VARCHAR2(20) UNIQUE NOT NULL,
    telefone VARCHAR2(15),
    email VARCHAR2(100)
);

CREATE TABLE ATENDIMENTO (
    id_atendimento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_atendimento DATE DEFAULT SYSDATE,
    descricao VARCHAR2(255),
    id_paciente NUMBER NOT NULL,
    id_enfermeiro NUMBER NOT NULL,
    
    CONSTRAINT fk_paciente
        FOREIGN KEY (id_paciente)
        REFERENCES PACIENTE(id_paciente)
        ON DELETE CASCADE,

    CONSTRAINT fk_enfermeiro
        FOREIGN KEY (id_enfermeiro)
        REFERENCES ENFERMEIRO(id_enfermeiro)
        ON DELETE SET NULL
);

CREATE TABLE MEDICO (
    id_medico NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    crm VARCHAR2(20) UNIQUE NOT NULL,
    especialidade VARCHAR2(50),
    telefone VARCHAR2(15)
);

ALTER TABLE ATENDIMENTO
ADD id_medico NUMBER,
ADD CONSTRAINT fk_atendimento_medico,
FOREIGN KEY (id_medico);
REFERENCES MEDICO (id_medico);
