-------------------------------------------------------------
-- TABELA: SETOR
-------------------------------------------------------------
CREATE TABLE SETOR (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME_SETOR   VARCHAR2(200) NOT NULL,
    BLOCO        VARCHAR2(200),
    TIPO_SETOR   VARCHAR2(200)
);

-------------------------------------------------------------
-- TABELA: PACIENTE
-------------------------------------------------------------
CREATE TABLE PACIENTE (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME            VARCHAR2(200) NOT NULL,
    CPF             VARCHAR2(11) UNIQUE NOT NULL,
    PLANO           VARCHAR2(200),
    DATA_NASCIMENTO DATE NOT NULL
);

-------------------------------------------------------------
-- TABELA: MEDICO
-------------------------------------------------------------
CREATE TABLE MEDICO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME           VARCHAR2(200) NOT NULL,
    CRM            NUMBER UNIQUE NOT NULL,
    ESPECIALIDADE  VARCHAR2(200)
);

-------------------------------------------------------------
-- TABELA: ENFERMEIRO
-------------------------------------------------------------
CREATE TABLE ENFERMEIRO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME       VARCHAR2(200) NOT NULL,
    COREN      NUMBER UNIQUE NOT NULL,
    ID_SETOR   NUMBER,
    FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID)
);

-------------------------------------------------------------
-- TABELA: LEITO
-------------------------------------------------------------
CREATE TABLE LEITO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    STATUS_LEITO VARCHAR2(200),
    ID_SETOR NUMBER NOT NULL,
    FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID)
);

-------------------------------------------------------------
-- TABELA: EXAME
-------------------------------------------------------------
CREATE TABLE EXAME (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME        VARCHAR2(200) NOT NULL,
    TIPO_EXAME  VARCHAR2(200) NOT NULL,
    DESCRICAO   VARCHAR2(200)
);

-------------------------------------------------------------
-- TABELA: ATENDIMENTO
-------------------------------------------------------------
CREATE TABLE ATENDIMENTO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    AGENDAMENTO  DATE DEFAULT SYSDATE NOT NULL,
    DIAGNOSTICO  VARCHAR2(200),
    OBSERVACOES  VARCHAR2(200),
    DATA_ALTA    DATE,
    ID_PACIENTE  NUMBER NOT NULL,
    ID_MEDICO    NUMBER NOT NULL,
    ID_LEITO     NUMBER,

    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID),
    FOREIGN KEY (ID_MEDICO)   REFERENCES MEDICO(ID),
    FOREIGN KEY (ID_LEITO)    REFERENCES LEITO(ID)
);

-------------------------------------------------------------
-- TABELA: ATENDIMENTO_EXAME  (Relacionamento N:N)
-------------------------------------------------------------
CREATE TABLE ATENDIMENTO_EXAME (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    DATA_SOLICITACAO DATE NOT NULL,
    ID_ATENDIMENTO   NUMBER NOT NULL,
    ID_EXAME         NUMBER NOT NULL,

    FOREIGN KEY (ID_ATENDIMENTO) REFERENCES ATENDIMENTO(ID),
    FOREIGN KEY (ID_EXAME)       REFERENCES EXAME(ID)
);

-------------------------------------------------------------
-- TABELA: ATENDIMENTO_ENFERMEIRO (Relacionamento N:N)
-------------------------------------------------------------
CREATE TABLE ATENDIMENTO_ENFERMEIRO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_ATENDIMENTO NUMBER NOT NULL,
    ID_ENFERMEIRO  NUMBER NOT NULL,

    FOREIGN KEY (ID_ATENDIMENTO) REFERENCES ATENDIMENTO(ID),
    FOREIGN KEY (ID_ENFERMEIRO)  REFERENCES ENFERMEIRO(ID)
);

-------------------------------------------------------------
-- TABELA: FINANCEIRO
-------------------------------------------------------------
CREATE TABLE FINANCEIRO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_ATENDIMENTO NUMBER NOT NULL,
    VALOR          NUMBER(10,2) NOT NULL,
    TIPO_PAGAMENTO VARCHAR2(200),

    FOREIGN KEY (ID_ATENDIMENTO) REFERENCES ATENDIMENTO(ID)
);

-------------------------------------------------------------
-- TABELA: HISTORICO FINANCEIRO
-------------------------------------------------------------
CREATE TABLE HISTORICO_FINANCEIRO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_FINANCEIRO  NUMBER NOT NULL,
    CAMPO_ALTERADO VARCHAR2(200),
    VALOR_ANTIGO   VARCHAR2(200),
    VALOR_NOVO     VARCHAR2(200),
    DATA_ALTERACAO DATE DEFAULT SYSDATE,

    FOREIGN KEY (ID_FINANCEIRO) REFERENCES FINANCEIRO(ID)
);