-- SETOR
INSERT INTO SETOR (NOME_SETOR, BLOCO, TIPO_SETOR)
VALUES ('Emergencia', 'A', 'Atendimento');

-- PACIENTE
INSERT INTO PACIENTE (NOME, CPF, PLANO, DATA_NASCIMENTO)
VALUES ('Joao da Silva', '12345678900', 'Unimed', TO_DATE('12/05/1990', 'DD/MM/YYYY'));

-- MÉDICO
INSERT INTO MEDICO (NOME, CRM, ESPECIALIDADE)
VALUES ('Rodolfo', 12345, 'Clinico Geral');

-- ENFERMEIRO
INSERT INTO ENFERMEIRO (NOME, COREN, ID_SETOR)
VALUES ('Maria Souza', 54321, 1);

-- LEITO
INSERT INTO LEITO (STATUS_LEITO, ID_SETOR)
VALUES ('LIVRE', 1);

-- ATENDIMENTO
INSERT INTO ATENDIMENTO (
    DIAGNOSTICO, OBSERVACOES,
    ID_PACIENTE, ID_MEDICO, ID_LEITO
)
VALUES (
    'Dor de cabeca', 'Paciente estavel',
    1, 1, 1
);

-- EXAME
INSERT INTO EXAME (NOME, TIPO_EXAME, DESCRICAO)
VALUES ('Exame de Sangue', 'Laboratorio', 'Hemograma Completo');

-- ATENDIMENTO_EXAME
INSERT INTO ATENDIMENTO_EXAME (DATA_SOLICITACAO, ID_ATENDIMENTO, ID_EXAME)
VALUES (SYSDATE, 1, 1);

-- ATENDIMENTO_ENFERMEIRO
INSERT INTO ATENDIMENTO_ENFERMEIRO (ID_ATENDIMENTO, ID_ENFERMEIRO)
VALUES (1, 1);

-- FINANCEIRO
INSERT INTO FINANCEIRO (ID_ATENDIMENTO, VALOR, TIPO_PAGAMENTO)
VALUES (1, 250.00, 'Cartao');

-- HISTORICO_FINANCEIRO
INSERT INTO HISTORICO_FINANCEIRO (ID_FINANCEIRO, CAMPO_ALTERADO, VALOR_ANTIGO, VALOR_NOVO)
VALUES (1, 'VALOR', '250.00', '300.00');
