-- CREATE
DROP TABLE CLIENTES PURGE;
CREATE TABLE CLIENTES (
    id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome    VARCHAR2(100) NOT NULL,
    email   VARCHAR(120) UNIQUE
);
-- DML: inserindo um aluno
    INSERT INTO CLIENTES (nome, email)
    VALUES ('Nicolas Melo', 'nicolasmelo15@gmail.com');

SELECT id, nome, email  FROM CLIENTES;

-- DML: inserindo um aluno
    INSERT INTO CLIENTES (nome, email)
    VALUES ('Pedro Alves', 'pedroalves2000@gmail.com');

    SELECT id, nome, email FROM CLIENTES;

-- DML: inserindo um aluno
    INSERT INTO CLIENTES (nome, email)
    VALUES ('Afonso Padilha', 'afonsopadilha10@gmail.com');

    SELECT id, nome, email FROM CLIENTES;

-- CREATE
DROP TABLE PRODUTOS PURGE;
CREATE TABLE PRODUTOS (
    id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome    VARCHAR2(100) NOT NULL,
    preco NUMBER(10,2) NOT NULL CHECK (preco >= 0),
    tipo    VARCHAR2(50) NOT NULL
);

-- Inserindo alguns produtos

    INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Notebook X', 3000, 'Notebook');
    INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Notebook Y', 3500,'Notebook');
    INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Celular Z', 2000, 'Celular');

UPDATE PRODUTOS 
SET preco = 3300
WHERE preco = 3000;

UPDATE PRODUTOS
SET preco = 3850
WHERE preco = 3500;

--  CREATE
DROP TABLE PEDIDOS PURGE;
CREATE TABLE PEDIDOS (
id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
cliente_id NUMBER NOT NULL,
produto_id NUMBER NOT NULL,
status  VARCHAR2(20) NOT NULL CHECK (status IN ('ABERTO', 'FINALIZADO', 'CANCELADO'))
);

-- Inserindo pedidos de teste

    INSERT INTO PEDIDOS (cliente_id, produto_id, status) VALUES (1, 1, 'ABERTO');
    INSERT INTO PEDIDOS (cliente_id, produto_id, status) VALUES (2,2, 'CANCELADO');
    INSERT INTO PEDIDOS (cliente_id, produto_id, status) VALUES (3, 3, 'FINALIZADO');
    INSERT INTO PEDIDOS (cliente_id, produto_id, status) VALUES (1,2, 'CANCELADO');

SELECT cliente_id, produto_id, status FROM PEDIDOS;

SELECT ID,status FROM PEDIDOS;

DELETE FROM PEDIDOS WHERE status = 'CANCELADO';

-- CREATE
CREATE TABLE CLIENTES_STG (
  nome  VARCHAR2(100) NOT NULL,
  email VARCHAR2(120) NOT NULL
);

INSERT ALL
  INTO CLIENTES_STG (nome, email) VALUES ('PEDRO Atualizado', 'pedroalves2000@gmail.com') -- já existe
  INTO CLIENTES_STG (nome, email) VALUES ('Daniela Nova', 'daniela@techplus.com') -- novo
SELECT 1 FROM dual;

MERGE INTO CLIENTES CL USING CLIENTES_STG STG
ON (CL.EMAIL = STG.EMAIL)
WHEN MATCHED THEN
    UPDATE SET CL.NOME = STG.NOME 
WHEN NOT MATCHED THEN
    INSERT (nome, email) VALUES ('Daniela Nova', 'daniela@techplus.com');